spring:
  datasource:
    url: jdbc:mysql://localhost:3306/cupid_connect?useSSL=false&serverTimezone=UTC
    username: root
    password: Baothang@1912
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        show_sql: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: noreply.and.subscribe999@gmail.com
    password: cvyuijwgfqybszrv
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  mvc:
    throw-exception-if-no-handler-found: true
  web:
    resources:
      add-mappings: true

server:
  error:
    whitelabel:
      enabled: false
  port: 8088

logging:
  level:
    root: info

api:
  prefix: api/v1
